#!/bin/sh
#PBS -q plgrid-testing
#PBS -l walltime=0:30:00
#PBS -l nodes=5:ppn=12
#PBS -A plgaksiazek2015a

mkdir -p /tmp/$USER/tpr

cd /tmp/$USER/tpr
module load tools/openmpi/1.6.3-gnu-4.1.2-ib
module load libs/gmp/5.1.2

cp -r ~/tpr/lab3/ .
cd lab3
make
./run.sh
