#!/bin/sh
#PBS -q plgrid-testing
#PBS -l walltime=0:01:00
#PBS -l nodes=1:ppn=12

mkdir -p /tmp/$USER/tpr/wyniki

cd /tmp/$USER/tpr
module load libs/boost/1.52.0
module load libs/gmp/5.1.2

cp -r ~/tpr/lab3/ .
make
mpiexec -n 12 ./pi 100000000 > wyniki
